export const GET_TEMPLATES_START = "GET_TEMPLATES_START";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATES_ERROR = "GET_TEMPLATES_ERROR";
export const CHANGE_TEMPLATE = "CHANGE_TEMPLATE";
